export const GET_ALL_USERS = 'Users/GET_ALL_USERS';
export const SET_ALL_USERS = 'Users/SET_ALL_USERS';

export const DELETE_USER_BY_ADMIN = 'Users/DELETE_USER_BY_ADMIN';
export const DELETE_USER_BY_ADMIN_SUCCESS = 'Users/DELETE_USER_BY_ADMIN_SUCCESS';
export const RESET_DELETE_USER_BY_ADMIN_SUCCESS = 'Users/RESET_DELETE_USER_BY_ADMIN_SUCCESS';
