export const DELETE_CATEGORY = 'Category/DELETE_CATEGORY';
export const DELETE_CATEGORY_SUCCESS = 'Category/DELETE_CATEGORY_SUCCESS';
export const RESET_DELETE_SUCCESS = 'Category/RESET_DELETE_SUCCESS';

export const CREATE_CATEGORIES = 'Category/CREATE_CATEGORIES';

export const UPDATE_CATEGORY_BY_ID = 'Category/UPDATE_CATEGORY_BY_ID';
