export const GET_PROFILE = 'Profile/GET_PROFILE';
export const SET_PROFILE = 'Profile/SET_PROFILE';
export const RESET_PROFILE = 'Profile/RESET_PROFILE';
export const EDIT_PHOTO_PROFILE = 'Profile/EDIT_PHOTO_PROFILE';
export const EDIT_PROFILE = 'Profile/EDIT_PROFILE';

export const DELETE_ACCOUNT = 'Profile/DELETE_ACCOUNT';
export const DELETE_ACCOUNT_SUCCESS = 'Profile/DELETE_ACCOUNT_SUCCESS';
export const RESET_DELETE_ACCOUNT_SUCCESS = 'Profile/RESET_DELETE_ACCOUNT_SUCCESS';
