export const GET_EVENT_BY_ID = 'DetailEvent/GET_EVENT_BY_ID';
export const SET_EVENT_BY_ID = 'DetailEvent/SET_EVENT_BY_ID';

export const INITIAL_PAYMENT = 'DetailEvent/INITIAL_PAYMENT';
export const INITIAL_PAYMENT_SUCCESS = 'DetailEvent/INITIAL_PAYMENT_SUCCESS';

export const CREATE_ORDER_EVENT = 'DetailEvent/CREATE_ORDER_EVENT';
export const CREATE_ORDER_EVENT_SUCCESS = 'DetailEvent/CREATE_ORDER_EVENT_SUCCESS';

export const UPDATE_EVENT_STATUS = 'DetailEvent/UPDATE_EVENT_STATUS';
export const UPDATE_EVENT_STATUS_SUCCESS = 'DetailEvent/UPDATE_EVENT_STATUS_SUCCESS';

export const CHECK_USER_ORDER = 'DetailEvent/CHECK_USER_ORDER';
export const SET_USER_ORDER_STATUS = 'DetailEvent/SET_USER_ORDER_STATUS';
