export const DELETE_LOCATION = 'Locations/DELETE_LOCATION';
export const DELETE_LOCATION_SUCCESS = 'Locations/DELETE_LOCATION_SUCCESS';
export const RESET_DELETE_SUCCESS = 'Locations/ RESET_DELETE_SUCCESS';

export const UPDATE_LOCATION_BY_ID = 'UPDATE_LOCATION_BY_ID';

export const CREATE_LOCATION = 'CREATE_LOCATION';
